version: '3.7'
services:
  cassandra:
    image: sapvs/cassandra-alpine:3.0.25-8
    expose:
      - "7199"
      - "7000"
      - "7001"
      - "9042"
      - "9160"
    env_file:
      - cassandra.env
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:alpine
    expose:
      - "6739"
    deploy:
      replicas: 1

  shorturl:
    depends_on:
      - cassandra
      - redis
    build:
      context: ..
      dockerfile: docker/shorturl/Dockerfile
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    expose:
      - "8080"
      - "8089"
    restart: on-failure

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
    depends_on:
      - shorturl
    ports:
      - "4000:4000"
