version: '3.7'
services:
  cassandra:
    image: cassandra:latest
    expose:
      - "7199"
      - "7000"
      - "7001"
      - "9042"
      - "9160"
    env_file:
      - cassandra.env
    restart: on-failure

  redis:
    image: redis:alpine
    expose:
      - "6739"
    deploy:
      replicas: 1

  tinyurl:
    depends_on:
      - cassandra
      - redis
    build:
      context: ..
      dockerfile: docker/tinyurl/Dockerfile
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    expose:
      - "8080"
      - "8089"
    restart: always
    scale: 1

  nginx:
    image: nginx:alpine
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
    depends_on:
      - tinyurl
    ports:
      - "4000:4000"
